// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"context"
	"fmt"
	"strconv"
	"testing"

	"career_backend/internal/dal/db/model"

	"gorm.io/gen"
	"gorm.io/gen/field"
	"gorm.io/gorm/clause"
)

func init() {
	InitializeDB()
	err := _gen_test_db.AutoMigrate(&model.Company{})
	if err != nil {
		fmt.Printf("Error: AutoMigrate(&model.Company{}) fail: %s", err)
	}
}

func Test_companyQuery(t *testing.T) {
	company := newCompany(_gen_test_db)
	company = *company.As(company.TableName())
	_do := company.WithContext(context.Background()).Debug()

	primaryKey := field.NewString(company.TableName(), clause.PrimaryKey)
	_, err := _do.Unscoped().Where(primaryKey.IsNotNull()).Delete()
	if err != nil {
		t.Error("clean table <company> fail:", err)
		return
	}

	_, ok := company.GetFieldByName("")
	if ok {
		t.Error("GetFieldByName(\"\") from company success")
	}

	err = _do.Create(&model.Company{})
	if err != nil {
		t.Error("create item in table <company> fail:", err)
	}

	err = _do.Save(&model.Company{})
	if err != nil {
		t.Error("create item in table <company> fail:", err)
	}

	err = _do.CreateInBatches([]*model.Company{{}, {}}, 10)
	if err != nil {
		t.Error("create item in table <company> fail:", err)
	}

	_, err = _do.Select(company.ALL).Take()
	if err != nil {
		t.Error("Take() on table <company> fail:", err)
	}

	_, err = _do.First()
	if err != nil {
		t.Error("First() on table <company> fail:", err)
	}

	_, err = _do.Last()
	if err != nil {
		t.Error("First() on table <company> fail:", err)
	}

	_, err = _do.Where(primaryKey.IsNotNull()).FindInBatch(10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatch() on table <company> fail:", err)
	}

	err = _do.Where(primaryKey.IsNotNull()).FindInBatches(&[]*model.Company{}, 10, func(tx gen.Dao, batch int) error { return nil })
	if err != nil {
		t.Error("FindInBatches() on table <company> fail:", err)
	}

	_, err = _do.Select(company.ALL).Where(primaryKey.IsNotNull()).Order(primaryKey.Desc()).Find()
	if err != nil {
		t.Error("Find() on table <company> fail:", err)
	}

	_, err = _do.Distinct(primaryKey).Take()
	if err != nil {
		t.Error("select Distinct() on table <company> fail:", err)
	}

	_, err = _do.Select(company.ALL).Omit(primaryKey).Take()
	if err != nil {
		t.Error("Omit() on table <company> fail:", err)
	}

	_, err = _do.Group(primaryKey).Find()
	if err != nil {
		t.Error("Group() on table <company> fail:", err)
	}

	_, err = _do.Scopes(func(dao gen.Dao) gen.Dao { return dao.Where(primaryKey.IsNotNull()) }).Find()
	if err != nil {
		t.Error("Scopes() on table <company> fail:", err)
	}

	_, _, err = _do.FindByPage(0, 1)
	if err != nil {
		t.Error("FindByPage() on table <company> fail:", err)
	}

	_, err = _do.ScanByPage(&model.Company{}, 0, 1)
	if err != nil {
		t.Error("ScanByPage() on table <company> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrInit()
	if err != nil {
		t.Error("FirstOrInit() on table <company> fail:", err)
	}

	_, err = _do.Attrs(primaryKey).Assign(primaryKey).FirstOrCreate()
	if err != nil {
		t.Error("FirstOrCreate() on table <company> fail:", err)
	}

	var _a _another
	var _aPK = field.NewString(_a.TableName(), "id")

	err = _do.Join(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("Join() on table <company> fail:", err)
	}

	err = _do.LeftJoin(&_a, primaryKey.EqCol(_aPK)).Scan(map[string]interface{}{})
	if err != nil {
		t.Error("LeftJoin() on table <company> fail:", err)
	}

	_, err = _do.Not().Or().Clauses().Take()
	if err != nil {
		t.Error("Not/Or/Clauses on table <company> fail:", err)
	}
}

var CompanyGetUserByUsernameTestCase = []TestCase{}

func Test_company_GetUserByUsername(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyGetUserByUsernameTestCase {
		t.Run("GetUserByUsername_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByUsername(tt.Input.Args[0].(string))
			assert(t, "GetUserByUsername", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByUsername", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyGetUserByPhoneTestCase = []TestCase{}

func Test_company_GetUserByPhone(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyGetUserByPhoneTestCase {
		t.Run("GetUserByPhone_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByPhone(tt.Input.Args[0].(string))
			assert(t, "GetUserByPhone", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByPhone", res2, tt.Expectation.Ret[1])
		})
	}
}

var CompanyGetUserByEmailTestCase = []TestCase{}

func Test_company_GetUserByEmail(t *testing.T) {
	company := newCompany(_gen_test_db)
	do := company.WithContext(context.Background()).Debug()

	for i, tt := range CompanyGetUserByEmailTestCase {
		t.Run("GetUserByEmail_"+strconv.Itoa(i), func(t *testing.T) {
			res1, res2 := do.GetUserByEmail(tt.Input.Args[0].(string))
			assert(t, "GetUserByEmail", res1, tt.Expectation.Ret[0])
			assert(t, "GetUserByEmail", res2, tt.Expectation.Ret[1])
		})
	}
}
